name: Testing deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Balle
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 172.232.133.47
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          kill -9 $(pgrep npm)
          kill -9 $(fuser 3000/tcp 2>/dev/null)
          cd /root/react-test-deploy
          git pull
          npm run dev