name: Testing deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Balle
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 172.232.133.47
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          systemctl stop website
          cd /root/react-test-deploy
          git pull
          systemctl start website